AWSTemplateFormatVersion: 2010-09-09
Description: "Test template"
Transform: AWS::Serverless-2016-10-31

Resources:
  rLambdaTest:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub "Lambda Test"
      CodeUri: ./build/lambda-test
      Handler: index.handler
      Timeout: 30
      MemorySize: 512
      Runtime: nodejs14.x